### PR TITLE
Testing enumerable methods with Rspec

### PR DESCRIPTION
**Pull request by Zubenna**
## In this pull request, we did the following
- Wrote tests for my_each enumerable method
- Wrote tests for my_each_with_index enumerable method
- Wrote tests for my_any enumerable method
- Wrote tests for my_all enumerable method
- Wrote tests for my_count enumerable method
- Wrote tests for my_none enumerable method
- Wrote tests for my_map enumerable method
- Wrote tests for my_inject enumerable method

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Nice try :clap: 
You have done well in writing your tests. Your test cases look fine but we need to put some things in order before we can merge this PR. Currently executing `rspec` shows `no examples found`. Let's see how to fix that.
- [ ] move the contents of `ruby_testing` folder to the root folder and delete that folder. you don't need it.
- [ ] change your import statement from `require '...'` to `require_relative '...'`
- [ ] send for another review once done

### Martin Afani

**Comment by Zubenna** [comment]
Recommendations have been implemented. You can now run tests by typing rspec in the project root.

**Review by maelfosso — COMMENTED** [review]
# Changes required :red_circle: 

Hello,

Thanks for applying the suggested changes. Now, `rspec` is returning answers.
I tweaked a bit your tests and I add this test in `#my_each` section
```rb
it 'It pass test when a given block' do
      block = proc { |num| num < 4 }
      expect(test_array.my_each(&block)).to eq(test_array.each(&block))
    end
```
But I got this error
```rb
$ rspec spec/custom_enumerable_spec.rb 
.....F..0123[:w, 3]0[:x, 4]1[:y, 2]2[:z, 6]3..........................

Failures:

  1) Enumerable#my_each after calling the given block once for each element in self, returns the array itself
     Failure/Error: expect(test_array.my_each(&block)).to eq(test_array.each(&block))
     
       expected: [5, 7, 9, 5]
            got: nil
     
       (compared using ==)
     # ./spec/custom_enumerable_spec.rb:29:in `block (3 levels) in <top (required)>'

Finished in 0.02134 seconds (files took 0.10918 seconds to load)
34 examples, 1 failure

Failed examples:

rspec ./spec/custom_enumerable_spec.rb:27 # Enumerable#my_each after calling the given block once for each element in self, returns the array itsel
```

Kindly fix it and submit a new code review request
Thanks

Mael FOSSO

**Comment by Zubenna** [comment]
Requested change has been implemented.

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

**Pull request merged**
